export const DEMO_DATA = {
  PROFILE: {
    avatar_url: '/hal.jpg',
    email: 'hal@example.com',
    family_id: 1,
    full_name: 'Hal',
    id: 'user-hal-001',
    phone: '+1234567890',
    socials: {
      twitter: '@hal',
      instagram: '@hal_ig',
    },
  },
  FAMILY: {
    created_at: '2025-01-01T10:00:00Z',
    id: 1,
    image: '/malcolm.webp',
    invitation_token: 'abc123def456',
    owner: 'user-hal-001',
    settings: {
      notifications: true,
      theme: 'light',
    },
    title: 'Malcolm family',
  },
  MEMBERS_IMAGE_MAP: {
    'user-hal-001': '/hal.jpg',
    'user-louis-002': '/lois.jpg',
  },
  MEMBERS: [
    {
      created_at: '2025-01-01T10:00:00Z',
      email: 'hal@example.com',
      family_id: 1,
      id: 1,
      is_owner: true,
      profile_id: 'user-hal-001',
      profiles: {
        avatar_url: '/hal.jpg',
        email: 'hal@example.com',
        family_id: 1,
        full_name: 'Hal',
        id: 'user-hal-001',
        phone: '+1234567890',
        socials: {
          twitter: '@hal',
          instagram: '@hal_ig',
        },
      },
      role: 'Parent',
      status: 'active',
    },
    {
      created_at: '2025-01-02T12:00:00Z',
      email: 'louis@example.com',
      family_id: 1,
      id: 2,
      is_owner: false,
      profile_id: 'user-louis-002',
      role: 'Sibling',
      status: 'active',
      profiles: {
        avatar_url: 'https://example.com/avatar_louis.jpg',
        email: 'louis@example.com',
        family_id: 1,
        full_name: 'Louis',
        id: 'user-louis-002',
        phone: '+0987654321',
        socials: {
          twitter: '@louis',
          instagram: '@louis_ig',
        },
        family: { id: 1 },
      },
    },
  ],
  FINANCIAL_RECORDS: [
    {
      amount: 140.08,
      category: 'Personal',
      created_at: '2025-05-18T05:03:05.266Z',
      family_id: 1,
      id: 1,
      note: '',
      profile_id: 'user-louis-002',
      profiles: {
        id: 'user-louis-002',
        full_name: 'Louis',
        avatar_url: 'lois.jpg',
      },
    },
    {
      amount: 45.56,
      category: 'Food',
      created_at: '2025-05-15T05:03:05.266Z',
      family_id: 1,
      id: 2,
      note: '',
      profile_id: 'user-hal-001',
      profiles: {
        id: 'user-hal-001',
        full_name: 'Hal',
        avatar_url: '/hal.jpg',
      },
    },
    {
      amount: 280.32,
      category: 'Medical',
      created_at: '2025-05-03T05:03:05.266Z',
      family_id: 1,
      id: 3,
      note: 'Split bill',
      profile_id: 'user-hal-001',
      profiles: {
        id: 'user-hal-001',
        full_name: 'Hal',
        avatar_url: '/hal.jpg',
      },
    },
    {
      amount: 366.94,
      category: 'Food',
      created_at: '2025-05-27T05:03:05.266Z',
      family_id: 1,
      id: 4,
      note: 'Split bill',
      profile_id: 'user-louis-002',
      profiles: {
        id: 'user-louis-002',
        full_name: 'Louis',
        avatar_url: 'lois.jpg',
      },
    },
    {
      amount: 73.07,
      category: 'Home',
      created_at: '2025-05-01T05:03:05.266Z',
      family_id: 1,
      id: 5,
      note: 'Paid via card',
      profile_id: 'user-louis-002',
      profiles: {
        id: 'user-louis-002',
        full_name: 'Louis',
        avatar_url: 'lois.jpg',
      },
    },
    {
      amount: 29.16,
      category: 'Entertainment',
      created_at: '2025-05-06T05:03:05.266Z',
      family_id: 1,
      id: 6,
      note: 'Paid via card',
      profile_id: 'user-hal-001',
      profiles: {
        id: 'user-hal-001',
        full_name: 'Hal',
        avatar_url: '/hal.jpg',
      },
    },
    {
      amount: 228.81,
      category: 'Entertainment',
      created_at: '2025-05-25T05:03:05.266Z',
      family_id: 1,
      id: 7,
      note: '',
      profile_id: 'user-louis-002',
      profiles: {
        id: 'user-louis-002',
        full_name: 'Louis',
        avatar_url: 'lois.jpg',
      },
    },
    {
      amount: 41.06,
      category: 'Entertainment',
      created_at: '2025-05-15T05:03:05.266Z',
      family_id: 1,
      id: 8,
      note: '',
      profile_id: 'user-louis-002',
      profiles: {
        id: 'user-louis-002',
        full_name: 'Louis',
        avatar_url: 'lois.jpg',
      },
    },
    {
      amount: 75.73,
      category: 'Medical',
      created_at: '2025-05-04T05:03:05.266Z',
      family_id: 1,
      id: 9,
      note: 'Paid via card',
      profile_id: 'user-louis-002',
      profiles: {
        id: 'user-louis-002',
        full_name: 'Louis',
        avatar_url: 'lois.jpg',
      },
    },
    {
      amount: 308.48,
      category: 'Fees',
      created_at: '2025-05-10T05:03:05.266Z',
      family_id: 1,
      id: 10,
      note: '',
      profile_id: 'user-louis-002',
      profiles: {
        id: 'user-louis-002',
        full_name: 'Louis',
        avatar_url: 'lois.jpg',
      },
    },
    {
      amount: 388.13,
      category: 'Transport',
      created_at: '2025-05-23T05:03:05.266Z',
      family_id: 1,
      id: 11,
      note: 'Split bill',
      profile_id: 'user-hal-001',
      profiles: {
        id: 'user-hal-001',
        full_name: 'Hal',
        avatar_url: '/hal.jpg',
      },
    },
    {
      amount: 361.16,
      category: 'Subscription',
      created_at: '2025-05-04T05:03:05.266Z',
      family_id: 1,
      id: 12,
      note: 'Paid via card',
      profile_id: 'user-louis-002',
      profiles: {
        id: 'user-louis-002',
        full_name: 'Louis',
        avatar_url: 'lois.jpg',
      },
    },
    {
      amount: 226.36,
      category: 'Shopping',
      created_at: '2025-05-25T05:03:05.266Z',
      family_id: 1,
      id: 13,
      note: 'Split bill',
      profile_id: 'user-hal-001',
      profiles: {
        id: 'user-hal-001',
        full_name: 'Hal',
        avatar_url: '/hal.jpg',
      },
    },
    {
      amount: 395.65,
      category: 'Food',
      created_at: '2025-05-01T05:03:05.266Z',
      family_id: 1,
      id: 14,
      note: '',
      profile_id: 'user-louis-002',
      profiles: {
        id: 'user-louis-002',
        full_name: 'Louis',
        avatar_url: 'lois.jpg',
      },
    },
    {
      amount: 131.79,
      category: 'Vacation',
      created_at: '2025-05-07T05:03:05.266Z',
      family_id: 1,
      id: 15,
      note: 'Reimbursed',
      profile_id: 'user-hal-001',
      profiles: {
        id: 'user-hal-001',
        full_name: 'Hal',
        avatar_url: '/hal.jpg',
      },
    },
    {
      amount: 95.61,
      category: 'Gift',
      created_at: '2025-05-22T05:03:05.266Z',
      family_id: 1,
      id: 16,
      note: '',
      profile_id: 'user-hal-001',
      profiles: {
        id: 'user-hal-001',
        full_name: 'Hal',
        avatar_url: '/hal.jpg',
      },
    },
    {
      amount: 229.3,
      category: 'Others',
      created_at: '2025-05-11T05:03:05.266Z',
      family_id: 1,
      id: 17,
      note: '',
      profile_id: 'user-hal-001',
      profiles: {
        id: 'user-hal-001',
        full_name: 'Hal',
        avatar_url: '/hal.jpg',
      },
    },
    {
      amount: 286.88,
      category: 'Subscription',
      created_at: '2025-05-13T05:03:05.266Z',
      family_id: 1,
      id: 18,
      note: 'Split bill',
      profile_id: 'user-louis-002',
      profiles: {
        id: 'user-louis-002',
        full_name: 'Louis',
        avatar_url: 'lois.jpg',
      },
    },
    {
      amount: 379.66,
      category: 'Emergency',
      created_at: '2025-05-24T05:03:05.266Z',
      family_id: 1,
      id: 19,
      note: '',
      profile_id: 'user-louis-002',
      profiles: {
        id: 'user-louis-002',
        full_name: 'Louis',
        avatar_url: 'lois.jpg',
      },
    },
    {
      amount: 267.66,
      category: 'Medical',
      created_at: '2025-05-13T05:03:05.266Z',
      family_id: 1,
      id: 20,
      note: 'Paid via card',
      profile_id: 'user-louis-002',
      profiles: {
        id: 'user-louis-002',
        full_name: 'Louis',
        avatar_url: 'lois.jpg',
      },
    },
  ],
  LISTS: [
    {
      created_at: '2025-05-01T10:00:00Z',
      family_id: 1,
      icon: '🥬',
      id: 1,
      index: 0,
      title: 'Groceries',
      tasks: [
        {
          assigned_to: 'user-hal-001',
          created_at: '2025-05-01T10:10:00Z',
          created_by: 'user-hal-001',
          deadline: '2025-05-21T18:00:00Z',
          id: 1,
          index: 0,
          is_completed: false,
          is_urgent: true,
          list_id: 1,
          title: 'Buy milk',
          updated_at: null,
        },
        {
          assigned_to: 'user-louis-002',
          created_at: '2025-05-01T10:15:00Z',
          created_by: 'user-hal-001',
          deadline: '2025-05-22T12:00:00Z',
          id: 2,
          index: 1,
          is_completed: false,
          is_urgent: false,
          list_id: 1,
          title: 'Buy eggs',
          updated_at: null,
        },
        {
          assigned_to: null,
          created_at: '2025-05-01T10:20:00Z',
          created_by: 'user-louis-002',
          deadline: null,
          id: 3,
          index: 2,
          is_completed: true,
          is_urgent: false,
          list_id: 1,
          title: 'Buy bread',
          updated_at: '2025-05-20T11:00:00Z',
        },
      ],
    },
    {
      created_at: '2025-05-05T09:00:00Z',
      family_id: 1,
      icon: '✅',
      id: 2,
      index: 1,
      title: 'To-do',
      tasks: [
        {
          assigned_to: 'user-hal-001',
          created_at: '2025-05-05T09:05:00Z',
          created_by: 'user-hal-001',
          deadline: '2025-05-25T14:00:00Z',
          id: 4,
          index: 0,
          is_completed: false,
          is_urgent: true,
          list_id: 2,
          title: 'Call the electrician',
          updated_at: null,
        },
        {
          assigned_to: 'user-louis-002',
          created_at: '2025-05-05T09:10:00Z',
          created_by: 'user-louis-002',
          deadline: null,
          id: 5,
          index: 1,
          is_completed: false,
          is_urgent: false,
          list_id: 2,
          title: 'Renew internet plan',
          updated_at: null,
        },
        {
          assigned_to: null,
          created_at: '2025-05-05T09:15:00Z',
          created_by: 'user-hal-001',
          deadline: '2025-05-26T12:00:00Z',
          id: 6,
          index: 2,
          is_completed: true,
          is_urgent: false,
          list_id: 2,
          title: 'Check gas levels',
          updated_at: '2025-05-19T10:00:00Z',
        },
      ],
    },
    {
      created_at: '2025-05-10T08:30:00Z',
      family_id: 1,
      icon: '🛍️',
      id: 3,
      index: 2,
      title: 'To-Shop',
      tasks: [
        {
          assigned_to: 'user-louis-002',
          created_at: '2025-05-10T08:35:00Z',
          created_by: 'user-hal-001',
          deadline: null,
          id: 7,
          index: 0,
          is_completed: false,
          is_urgent: false,
          list_id: 3,
          title: 'New bedsheets',
          updated_at: null,
        },
        {
          assigned_to: 'user-hal-001',
          created_at: '2025-05-10T08:40:00Z',
          created_by: 'user-louis-002',
          deadline: '2025-05-24T16:00:00Z',
          id: 8,
          index: 1,
          is_completed: true,
          is_urgent: false,
          list_id: 3,
          title: 'LED lamp',
          updated_at: '2025-05-18T09:00:00Z',
        },
        {
          assigned_to: null,
          created_at: '2025-05-10T08:45:00Z',
          created_by: 'user-hal-001',
          deadline: null,
          id: 9,
          index: 2,
          is_completed: false,
          is_urgent: true,
          list_id: 3,
          title: 'Curtains',
          updated_at: null,
        },
        {
          assigned_to: 'user-louis-002',
          created_at: '2025-05-10T08:50:00Z',
          created_by: 'user-louis-002',
          deadline: null,
          id: 10,
          index: 3,
          is_completed: true,
          is_urgent: false,
          list_id: 3,
          title: 'Socks pack',
          updated_at: '2025-05-20T10:30:00Z',
        },
      ],
    },
  ],
};
